#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD113FCAC3C4E599F (Nikolaus@rath.org)
#
Name     : fuse
Version  : 3.2.6
Release  : 28
URL      : https://github.com/libfuse/libfuse/releases/download/fuse-3.2.6/fuse-3.2.6.tar.xz
Source0  : https://github.com/libfuse/libfuse/releases/download/fuse-3.2.6/fuse-3.2.6.tar.xz
Source99 : https://github.com/libfuse/libfuse/releases/download/fuse-3.2.6/fuse-3.2.6.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: fuse-bin
Requires: fuse-config
Requires: fuse-lib
Requires: fuse-license
Requires: fuse-man
BuildRequires : buildreq-meson
BuildRequires : pkgconfig(udev)
Patch1: build.patch

%description
libfuse
=======
About
-----
FUSE (Filesystem in Userspace) is an interface for userspace programs
to export a filesystem to the Linux kernel. The FUSE project consists
of two components: the *fuse* kernel module (maintained in the regular
kernel repositories) and the *libfuse* userspace library (maintained
in this repository). libfuse provides the reference implementation
for communicating with the FUSE kernel module.

%package bin
Summary: bin components for the fuse package.
Group: Binaries
Requires: fuse-config
Requires: fuse-license
Requires: fuse-man

%description bin
bin components for the fuse package.


%package config
Summary: config components for the fuse package.
Group: Default

%description config
config components for the fuse package.


%package dev
Summary: dev components for the fuse package.
Group: Development
Requires: fuse-lib
Requires: fuse-bin
Provides: fuse-devel

%description dev
dev components for the fuse package.


%package lib
Summary: lib components for the fuse package.
Group: Libraries
Requires: fuse-license

%description lib
lib components for the fuse package.


%package license
Summary: license components for the fuse package.
Group: Default

%description license
license components for the fuse package.


%package man
Summary: man components for the fuse package.
Group: Default

%description man
man components for the fuse package.


%prep
%setup -q -n fuse-3.2.6
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535824471
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/doc/fuse
cp COPYING %{buildroot}/usr/share/doc/fuse/COPYING
cp COPYING.LIB %{buildroot}/usr/share/doc/fuse/COPYING.LIB
DESTDIR=%{buildroot} ninja -C builddir install
## install_append content
ln -s /usr/bin/fusermount3 %{buildroot}/usr/bin/fusermount
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fusermount
/usr/bin/fusermount3
/usr/sbin/mount.fuse3

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/99-fuse3.rules

%files dev
%defattr(-,root,root,-)
/usr/include/fuse3/cuse_lowlevel.h
/usr/include/fuse3/fuse.h
/usr/include/fuse3/fuse_common.h
/usr/include/fuse3/fuse_lowlevel.h
/usr/include/fuse3/fuse_opt.h
/usr/lib64/libfuse3.so
/usr/lib64/pkgconfig/fuse3.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libfuse3.so.3
/usr/lib64/libfuse3.so.3.2.6

%files license
%defattr(-,root,root,-)
/usr/share/doc/fuse/COPYING
/usr/share/doc/fuse/COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/fusermount3.1.gz
/usr/share/man/man8/mount.fuse3.8.gz
